config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get "reports/index"
  end
  # get 'chats/show'
  get "searches/search"
  root "public/homes#top"
  get "/search", to: "searches#search"

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admins, path: "admin", controllers: {
    sessions: "admin/sessions"
  }, path_names: { sign_in: "" }
  # 未認証の管理者がアクセスした際のリダイレクト先を指定
  unauthenticated :admin do
    root "admin/sessions#new", as: :unauthenticated_admin_root
  end

  # 会員用
  # URL /customers/sign_in ...
  devise_for :customers, controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  # ゲストユーザー
  devise_scope :customer do
    post "customers/guest_sign_in", to: "public/sessions#guest_sign_in", as: :customers_guest_sign_in
  end

  # 会員側のルーティング
  namespace :public do
    #画像感情分析
    post 'analyze_emotion', to: 'emotions#analyze'  # public側でのみ感情分析機能を使用
    # aboutページ
    get "/about", to: "homes#about"
    # マイページ
    get "mypage", to: "customers#mypage", as: "mypage"
    # ユーザー退会処理（ステータス更新）
    delete "customers/withdraw", to: "customers#withdraw", as: "withdraw_customer"
    resources :customers, only: [:show, :edit, :update, :destroy] do
      member do
        get :following, :followers
      end
      resource :relationships, only: [:create, :destroy]
    end
    resources :posts, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
      resources :post_comments, only: [:create, :destroy]
      resource :favorite, only: [:create, :destroy]
      collection do
        get :favorites  # 自分がいいねした投稿一覧ページ
      end
    end
    resources :chats, only: [:create, :show, :destroy] do
      delete :destroy_all, on: :collection
    end
    # チャット通知
    resources :notifications, only: [:index] do
      member do
        patch :mark_as_read
      end
      collection do
        patch :mark_all_as_read
      end
    end
    resource :session, only: [:new, :create, :destroy]
    resources :relationships, only: [:create, :destroy]
    resources :reports, only: [:new, :create]
  end

  # 管理側のルーティング
  namespace :admin do
    # root to: "customers#index" # ログイン後のリダイレクト先を会員一覧に設定
    get "dashboard", to: "dashboard#index"
    resources :customers, only: [:index, :show, :destroy, :edit, :update]
    resources :posts, only: [:index, :show, :destroy, :edit, :update]
    resources :post_comments, only: [:index, :destroy]
    resources :reports, only: [:index, :show, :destroy] do
     member do
       delete :delete_content
       patch :ignore
       patch :toggle
     end
   end
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :authenticate_customer!
  def search
    @model = params[:model]
    @content = params[:content]
    @method = params[:method]
    if @model == "customer"
      @records = Customer.search_for(@content, @method)
    elsif @model == "post"
      @records = Post.search_for(@content, @method)
    else
      @records = []
    end
  end
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/_form.html.erb
<% if customer_signed_in? %>
  <%= form_with url: search_path, method: :get, local: true, html: { class: 'mt-4' } do |f| %>
    <div class="form-row align-items-center">
      <div class="col-auto">
        <%= f.text_field :content, class: 'form-control mb-2' %>
      </div>
      <div class="col-auto">
        <%= f.select :model, options_for_select({ "Customer" => "customer", "Post" => "post" }), {}, { class: 'form-control mb-2' } %>
      </div>
      <div class="col-auto">
        <button type="submit" class="btn btn-primary mb-2"style="width: 150px;">
          <i class="fa-solid fa-magnifying-glass"></i> 
        </button>
      </div>
    </div>
  <% end %>
<% end %>

app/views/searches/search.html.erb
<div class="container d-flex flex-column align-items-center">
 
  <% if @model == 'post' %>
    <h3 class="text-center mt-4">Posts search for "<%= @content %>"</h3>
    <% if @records.present? %>
      <%= render 'public/posts/index', posts: @records %>
    <% else %>
      <!-- 検索結果がない場合に表示される -->
      <p class="text-center mt-4">No posts found.</p>
    <% end %>
  <% elsif @model == 'customer' %>
    <h3 class="text-center mt-4">Customers search for "<%= @content %>"</h3>
    <% if @records.present? %>
      <% @records.each do |customer| %>
        <%= render 'public/customers/index', customer: customer %>
      <% end %>
    <% else %>
      <!-- 検索結果がない場合に表示される -->
      <p class="text-center mt-4">No customers found.</p>
    <% end %>
  <% else %>
    <!-- モデルが指定されていない場合の表示 -->
    <p class="text-center mt-4">No results found.</p>
  <% end %>
</div>