config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get "reports/index"
  end
  # get 'chats/show'
  get "searches/search"
  root "public/homes#top"
  get "/search", to: "searches#search"

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admins, path: "admin", controllers: {
    sessions: "admin/sessions"
  }, path_names: { sign_in: "" }
  # 未認証の管理者がアクセスした際のリダイレクト先を指定
  unauthenticated :admin do
    root "admin/sessions#new", as: :unauthenticated_admin_root
  end

  # 会員用
  # URL /customers/sign_in ...
  devise_for :customers, controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  # ゲストユーザー
  devise_scope :customer do
    post "customers/guest_sign_in", to: "public/sessions#guest_sign_in", as: :customers_guest_sign_in
  end

  # 会員側のルーティング
  namespace :public do
    #画像感情分析
    post 'analyze_emotion', to: 'emotions#analyze'  # public側でのみ感情分析機能を使用
    # aboutページ
    get "/about", to: "homes#about"
    # マイページ
    get "mypage", to: "customers#mypage", as: "mypage"
    # ユーザー退会処理（ステータス更新）
    delete "customers/withdraw", to: "customers#withdraw", as: "withdraw_customer"
    resources :customers, only: [:show, :edit, :update, :destroy] do
      member do
        get :following, :followers
      end
      resource :relationships, only: [:create, :destroy]
    end
    resources :posts, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
      resources :post_comments, only: [:create, :destroy]
      resource :favorite, only: [:create, :destroy]
      collection do
        get :favorites  # 自分がいいねした投稿一覧ページ
      end
    end
    resources :chats, only: [:create, :show, :destroy] do
      delete :destroy_all, on: :collection
    end
    # チャット通知
    resources :notifications, only: [:index] do
      member do
        patch :mark_as_read
      end
      collection do
        patch :mark_all_as_read
      end
    end
    resource :session, only: [:new, :create, :destroy]
    resources :relationships, only: [:create, :destroy]
    resources :reports, only: [:new, :create]
  end

  # 管理側のルーティング
  namespace :admin do
    # root to: "customers#index" # ログイン後のリダイレクト先を会員一覧に設定
    get "dashboard", to: "dashboard#index"
    resources :customers, only: [:index, :show, :destroy, :edit, :update]
    resources :posts, only: [:index, :show, :destroy, :edit, :update]
    resources :post_comments, only: [:index, :destroy]
    resources :reports, only: [:index, :show, :destroy] do
     member do
       delete :delete_content
       patch :ignore
       patch :toggle
     end
   end
  end
end

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h3><%= pluralize(obj.errors.count, "error") %> prohibited this obj from being saved:</h3>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="bg-dark text-white">
  <div class="container">
    <div class="row no-gutters">
      <div class="col-md-8">
        <p class="mt-3">It is an SNS community site where pet owners connect <br>by putting themselves in their cats’ shoes.</p>
      </div>
      <div class="col-md-3">
        <h6 class="text-white mt-3 mb-3">Link</h6>
        <ul class="p-0 list-unstyled">
          <li>
            <a class="text-white-50 ">株式会社 にゃんず</a>
          </li>
          <li>
            <a  class="text-white-50">プライバシーポリシー</a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <%= link_to root_path do %>
      <%= image_tag 'top_lo.png', alt: 'にゃんずbookロゴ', width: 200, style: ' margin: 0; padding: 0;' %>
    <% end %>
    
    <!-- ハンバーガーボタンの追加 -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav ml-auto">
        <% if admin_signed_in? %>
          <!-- 管理者ログイン中のナビゲーション -->
          <li><%= link_to admin_dashboard_path, class: 'nav-link text-light' do %><i class="fa-solid fa-chart-line"></i> ダッシュボード<% end %></li>
          <li><%= link_to  admin_customers_path, class: 'nav-link text-light' do %><i class="fa-solid fa-users"></i> Customer List<% end %></li>
          <li><%= link_to admin_posts_path, class: 'nav-link text-light' do %><i class="fa-regular fa-image"></i> Post List<% end %></li>
          <li><%= link_to admin_post_comments_path, class: 'nav-link text-light' do %><i class="fa-regular fa-image"></i> Comment List<% end %></li>
          <li class="nav-item"><%= link_to admin_reports_path, class: 'nav-link position-relative' do %>
            <i class="fa-solid fa-bell"></i>
            <% unread_reports_count = Report.where(is_checked: false).count %>
            <% if unread_reports_count > 0 %>
              <span class="badge badge-danger position-absolute" style="top: -5px; right: -5px;"><%= unread_reports_count %></span>
            <% end %>
          <% end %></li>
          <li><%= link_to destroy_admin_session_path, method: :delete, class: 'nav-link text-light' do %><i class="fas fa-sign-out-alt"></i> logout<% end %></li>
        <% elsif customer_signed_in? %>
          <!-- 顧客ログイン中のナビゲーション -->
          <li><%= link_to public_customer_path(current_customer), class: 'nav-link text-light' do %><i class="fas fa-home"></i> MyHome<% end %></li>
          <li><%= link_to public_mypage_path, class: 'nav-link text-light' do %><i class="fa-solid fa-cat"></i>MyPage<% end %></li>
          <li><%= link_to new_public_post_path, class: 'nav-link text-light' do %><i class="fa-solid fa-camera-retro"></i>NewPost<% end %></li>
          <li><%= link_to public_posts_path, class: 'nav-link text-light' do %><i class="fa-regular fa-image"></i> PostList<% end %></li>
          <li><%= link_to favorites_public_posts_path, class: 'nav-link text-light' do %><i class="fa-solid fa-heart"></i>いいねList<% end %></li>
          <li><%= link_to public_notifications_path, class: 'nav-link text-light' do %><i class="fa-solid fa-bell"></i> 通知
            <% if @unread_notifications_count > 0 %>
              <span class="badge badge-danger"><%= @unread_notifications_count %></span>
            <% end %>
          <% end %></li>
          <li><%= link_to destroy_customer_session_path, method: :delete, class: 'nav-link text-light' do %><i class="fas fa-sign-out-alt"></i> logout<% end %></li>
        <% else %>
          <!-- ログインしていない時のナビゲーション -->
          <li><%= link_to root_path, class: 'nav-link text-light' do %><i class="fas fa-home"></i> Home<% end %></li>
          <li><%= link_to public_about_path, class: 'nav-link text-light' do %><i class="fas fa-link"></i> About<% end %></li>
          <li><%= link_to new_customer_registration_path, class: 'nav-link text-light' do %><i class="fas fa-user-plus"></i> sign up<% end %></li>
          <li><%= link_to new_customer_session_path, class: 'nav-link text-light' do %><i class="fas fa-sign-in-alt"></i> login<% end %></li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NyansBookWbs</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/75e15c40a4.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column  <%= 'top-page-background' if current_page?(controller: 'public/homes', action: 'top') %>">
    <%= render 'layouts/header' %>
    <main class="mb-auto">

      <!-- フラッシュメッセージの表示 -->
      <% if notice %>
        <div class="notice"><%= notice %></div>
      <% end %>

      <% if alert %>
        <div class="alert"><%= alert %></div>
      <% end %>
      
      <% if flash[:emotion_analysis_result] %>
        <div class="alert alert-info">
          <%= flash[:emotion_analysis_result] %>
        </div>
      <% end %>

      <%= yield %>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>